db.url=jdbc:postgresql://localhost:5433/training
#db.url=jdbc:p6spy:postgresql://localhost:5433/training
db.user=postgres
db.pass=martin

db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeout=5000
db.pool.idleTimeout=60000
db.pool.maxLifetime=600000