db.url=jdbc:postgresql://localhost:5432/postgres
#db.url=jdbc:p6spy:postgresql://localhost:5432/training
db.user=postgres
db.pass=admin

db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeout=5000
db.pool.idleTimeout=60000
db.pool.maxLifetime=600000